"""Add_meal_type

Revision ID: b379ce3fa8db
Revises: 25074adf47d9
Create Date: 2026-02-11 13:46:37.069655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b379ce3fa8db'
down_revision: Union[str, Sequence[str], None] = '25074adf47d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meal', sa.Column('meal_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meal', 'meal_type')
    # ### end Alembic commands ###
